### PR TITLE
Choo 5 update

### PR DESCRIPTION
**Pull request by zapaiamarce**

### CODE REVIEW

**Comment by bengourley** [comment]
I haven't had the chance to use v5 yet, but merging assuming this works for you! Thanks.

**Comment by bengourley** [comment]
So it turns out I had published a v3 with this "stop" functionality. It'd be good to replay your updates on that branch, but I don't know if choo v5 has "stop()"?

https://github.com/bengourley/choo-resume/tree/stop

**Comment by yoshuawuyts** [comment]
Choo 5 doesn't have stop; we pulled out all of barracks and replaced it
with nanobus. You can use emitter.removeAllListeners from .use() tho which
I think should have the same effect as .stop() C:

**Comment by bengourley** [comment]
Thanks for the update! I'll have a stab at this when I get the chance to try v5 out for real if @qzapaia doesn't get there first.

**Comment by yoshuawuyts** [comment]
Woot!

**Comment by zapaiamarce** [comment]
Awesome. New PR coming right away

**Pull request merged**
